SELECT TNO, TITLE, TNAME
	FROM TEACHERS
	WHERE NOT EXISTS
		(SELECT *
		FROM TSC
		WHERE TEACHERS.TNO = TSC.TNO)

SELECT COURSES.CNO, COURSES.CNAME, COUNT(TSC.CNO)
	FROM COURSES, TSC
	WHERE COURSES.CNO = TSC.CNO
	GROUP BY COURSES.CNO, COURSES.CNAME
	ORDER BY COUNT(TSC.CNO) DESC

UPDATE TSC
	SET GRADE = GRADE - 0.5
	WHERE GRADE > 3.5 AND (SNO = 'S5' OR SNO = 'S6')


SELECT STUDENTS.SNO, SNAME, AVG(GRADE), SUM(HOURS)
	FROM STUDENTS, TSC
	WHERE STUDENTS.SNO = TSC.SNO
	GROUP BY STUDENTS.SNO, SNAME
	ORDER BY AVG(GRADE) ASC

SELECT DISTINCT TNO
	FROM TSC
	WHERE HOURS = (SELECT MAX(HOURS) FROM TSC)

SELECT TEACHERS.TNO, TITLE, TNAME, COUNT(DISTINCT CNO), SUM(HOURS)
	FROM TEACHERS JOIN TSC
	ON TEACHERS.TNO = TSC.TNO
	GROUP BY TEACHERS.TNO, TITLE, TNAME
	ORDER BY SUM(HOURS) ASC

--DROP TABLE IF EXISTS TEMP;

--CREATE TABLE TEMP AS
--	SELECT CNO, COUNT(DISTINCT SNO) AS ILE
--	FROM TSC
--	GROUP BY CNO
--
--SELECT TEMP.CNO, CNAME
--	FROM COURSES JOIN TEMP
--		ON COURSES.CNO = TEMP.CNO
--	WHERE ILE = (SELECT MIN(ILE)
--					FROM TEMP)

SELECT TNO
	FROM TSC
	WHERE HOURS =
	(SELECT MAX(HOURS) FROM TSC)

SELECT CNO, CNAME
	FROM COURSES
	WHERE CNO NOT IN
	(SELECT DISTINCT CNO
	FROM TSC)

SELECT STUDENTS.SNO, SNAME, AVG(GRADE)
	FROM STUDENTS JOIN TSC
	ON STUDENTS.SNO = TSC.SNO
	GROUP BY STUDENTS.SNO, SNAME
	ORDER BY AVG(GRADE) ASC

DROP TABLE TEACH_DATA
CREATE TABLE TEACH_DATA
	(TNO	CHAR(3),
	TNAME	CHAR(12),
	THOURS	INTEGER,
	TGAVG	FLOAT);

INSERT INTO TEACH_DATA
	SELECT TSC.TNO, TNAME, SUM(HOURS), AVG(GRADE)
	FROM TSC JOIN TEACHERS
	ON TSC.TNO = TEACHERS.TNO
	GROUP BY TSC.TNO, TNAME

SELECT * FROM TEACH_DATA

SELECT TNO, TITLE, TNAME
	FROM TEACHERS
	WHERE NOT EXISTS
		(SELECT TSC.TNO
		FROM TSC
		WHERE TSC.TNO = TEACHERS.TNO)

SELECT TSC.CNO, CNAME, COUNT(HOURS)
	FROM TSC, COURSES
	WHERE TSC.CNO = COURSES.CNO
	GROUP BY TSC.CNO, CNAME
	ORDER BY COUNT(HOURS) ASC

UPDATE TSC
	SET GRADE  = GRADE - 0.5
	WHERE GRADE IN (3.5, 4, 4.5, 5)
	AND (TSC.SNO = 'S2' OR TSC.SNO = 'S3')

DELETE FROM TEACHERS
	WHERE TNO = 'T2';
DELETE FROM TSC
	WHERE TNO = 'T2';
UPDATE TEACHERS
	SET SUPNO = NULL
	WHERE SUPNO = 'T2'

--DROP TABLE TDATA
--
--CREATE TABLE TDATA AS
--	SELECT TSC.TNO, TNAME, SUM(HOURS) AS THOURS, AVG(GRADE) AS TGAVG
--	FROM TSC JOIN TEACHERS
--	ON TSC.TNO = TEACHERS.TNO
--	GROUP BY TSC.TNO, TNAME
--	HAVING AVG(GRADE)>=4.0
--	ORDER BY TNAME ASC
--
--SELECT * FROM TDATA

SELECT TNO, TNAME
	FROM TEACHERS
	WHERE TNO IN
		(SELECT SUPNO
		FROM TEACHERS
		GROUP BY SUPNO
		HAVING COUNT(SUPNO) >= 2)

SELECT * FROM TEACHERS
WHERE SUPNO IS NOT NULL

SELECT * FROM TEACHERS
	WHERE TNO IN
	(SELECT SUPNO FROM TEACHERS)

SELECT SYEAR, AVG(GRADE) AS WYN
	FROM STUDENTS JOIN TSC
	ON STUDENTS.SNO = TSC.SNO
	GROUP BY SYEAR
	ORDER BY WYN DESC

DELETE FROM TSC
WHERE TNO = 'T5'

DELETE FROM TEACHERS
WHERE TNO = 'T5'

UPDATE TEACHERS SET SUPNO = NULL
WHERE SUPNO = 'T5'

UPDATE TSC SET GRADE = GRADE - 0.5
WHERE GRADE > 3.0 AND SNO IN ('S2', 'S3')

SELECT TNO, TNAME
FROM TEACHERS
WHERE TNO IN
( SELECT SUPNO
FROM TEACHERS
GROUP BY SUPNO
HAVING COUNT(*) >= 2)

SELECT COURSES.CNO, CNAME, COUNT(TSC.CNO)
FROM COURSES, TSC
WHERE TSC.CNO = COURSES.CNO
GROUP BY COURSES.CNO, CNAME
ORDER BY COUNT(TSC.CNO) DESC

SELECT DISTINCT TNO
FROM TSC
WHERE HOURS = (SELECT MAX(HOURS) FROM TSC)

SELECT CNO, CNAME
FROM COURSES
WHERE CNO NOT IN (SELECT CNO FROM TSC)




--SELECT CNO, CNAME
--FROM COURSES
--WHERE CNO NOT IN (SELECT CNO FROM TSC)



SELECT *
FROM TEACHERS
WHERE NOT SUPNO = 'NULL'




SELECT TNO, TNAME
FROM TEACHERS
WHERE TNO IN (SELECT SUPNO FROM TEACHERS GROUP BY SUPNO  HAVING COUNT(SUPNO) >= 2 )




--DROP TABLE TEMP
--
--CREATE TABLE TEMP AS
--SELECT CNO, COUNT(DISTINCT SNO) AS ILE
--FROM TSC
--GROUP BY CNO
--
--SELECT TEMP.CNO, CNAME
--FROM COURSES JOIN TEMP
--ON COURSES.CNO = TEMP.CNO
--WHERE ILE = (SELECT MAX(ILE) FROM TEMP)

SELECT STUDENTS.SNO, SNAME, AVG(GRADE)
FROM STUDENTS JOIN TSC
ON STUDENTS.SNO = TSC.TNO
GROUP BY STUDENTS.SNO, SNAME
ORDER BY AVG(GRADE)

SELECT TNO, TITLE, TNAME
FROM TEACHERS
WHERE NOT EXISTS
( SELECT TNO
FROM TSC
WHERE TSC.TNO = TEACHERS.TNO)

SELECT *
FROM TEACHERS
WHERE SUPNO IS NOT NULL

--CREATE TABLE TDATA AS
--SELECT TEACHERS.TNO, TNAME, SUM(HOURS) AS THOURS, AVG(GRADE) AS TAVG
--FROM TEACHERS JOIN TSC
--ON TEACHERS.TNO = TSC.TNO
--GROUP BY TEACHERS.TNO, TNAME
--HAVING TAVG>=4.0
--ORDER BY TNAME